#include <cstdint>
#include <cstring>
#include <cstdlib>
#include <cstdio>
#include <cmath>
#include <vector>
#include <algorithm>
#include <string>
#include <chrono>
#include <sys/socket.h>
#include <sys/un.h>
#include <unistd.h>
#include <csignal>

// ── Vendor ────────────────────────────────────────────────────────────────────
#include "vendor/stb_truetype.h"
#include "vendor/fpng.h"

// ── Embedded assets (generated by xxd) ───────────────────────────────────────
#include "gen/font_fraunces.h" // assets/Fraunces-Bold.ttf
#include "gen/font_dmmono.h"   // assets/DMMono-Medium.ttf
#include "gen/font_inter.h"    // assets/Inter-VariableFont_opsz,wght.ttf

// ── Theme system ─────────────────────────────────────────────────────────────
#include "themes.h"

// ── Glyph rasterization cache ─────────────────────────────────────────────────
#include "glyph_cache.h"

// ── Canvas size ───────────────────────────────────────────────────────────────
// The design is authored at 1200x630 (the OG-card reference — the universal
// minimum for WhatsApp/iMessage/Google Messages). BILLPREVIEW_SCALE rescales the
// WHOLE layout — canvas, positions, font sizes — at build time, trading softness
// for render + PNG-encode cost (both fall with the pixel count). The 1.91:1
// ratio is preserved, so previews still crop correctly.
//
//   -DBILLPREVIEW_SCALE=1.0    -> 1200x630  (default, crispest)
//   -DBILLPREVIEW_SCALE=0.667  ->  800x420
//   -DBILLPREVIEW_SCALE=0.5    ->  600x315  (~1/4 the pixels, softer)
#ifndef BILLPREVIEW_SCALE
#define BILLPREVIEW_SCALE 1.0f
#endif
static constexpr float SCALE = BILLPREVIEW_SCALE;
static constexpr int IMG_W = (int)(1200 * SCALE + 0.5f);
static constexpr int IMG_H = (int)(630 * SCALE + 0.5f);
static constexpr int CH = 4; // RGBA

// design-space (1200x630) pixel -> render-space. Every layout literal goes
// through these so one SCALE knob moves the whole card. Ratios (e.g. the rupee's
// 0.7 of the digit size) are NOT scaled — they are already relative.
static constexpr int SPX(float v) { return (int)(v * SCALE + 0.5f); }
static constexpr float SF(float v) { return v * SCALE; }

// Palette is now fully driven by the Theme system (see src/themes.h / themes.cpp).
// Themes are selected per-request via the optional 4th tab field in the protocol
// or fall back to an amount-based ladder (dark-purple → dark-slate).

// ── UDS ───────────────────────────────────────────────────────────────────────
static constexpr const char *SOCKET_PATH = "/tmp/billpreview.sock";

// ─────────────────────────────────────────────────────────────────────────────
// Canvas
// ─────────────────────────────────────────────────────────────────────────────
struct Canvas
{
    std::vector<uint8_t> px;
    int w, h;

    Canvas(int w, int h) : px(w * h * CH), w(w), h(h) {}

    // fill entire canvas with one colour
    void fill(RGBA c)
    {
        for (int i = 0; i < w * h; ++i)
        {
            px[i * CH + 0] = c.r;
            px[i * CH + 1] = c.g;
            px[i * CH + 2] = c.b;
            px[i * CH + 3] = c.a;
        }
    }

    // filled rectangle — no blending, solid
    void rect(int x, int y, int rw, int rh, RGBA c)
    {
        for (int row = y; row < y + rh; ++row)
        {
            if (row < 0 || row >= h)
                continue;
            for (int col = x; col < x + rw; ++col)
            {
                if (col < 0 || col >= w)
                    continue;
                uint8_t *p = px.data() + (row * w + col) * CH;
                p[0] = c.r;
                p[1] = c.g;
                p[2] = c.b;
                p[3] = c.a;
            }
        }
    }

    // blit a greyscale glyph bitmap with alpha blend onto canvas
    void blit_glyph(const uint8_t *bmp, int bw, int bh,
                    int dx, int dy, RGBA c)
    {
        for (int row = 0; row < bh; ++row)
        {
            for (int col = 0; col < bw; ++col)
            {
                int cx = dx + col, cy = dy + row;
                if (cx < 0 || cy < 0 || cx >= w || cy >= h)
                    continue;
                uint8_t alpha = bmp[row * bw + col];
                if (alpha == 0)
                    continue;
                uint8_t *p = px.data() + (cy * w + cx) * CH;
                // simple over blend
                uint16_t ia = 255 - alpha;
                p[0] = (uint8_t)((c.r * alpha + p[0] * ia) >> 8);
                p[1] = (uint8_t)((c.g * alpha + p[1] * ia) >> 8);
                p[2] = (uint8_t)((c.b * alpha + p[2] * ia) >> 8);
                p[3] = 255;
            }
        }
    }
};

// ─────────────────────────────────────────────────────────────────────────────
// UTF-8 — one validated decoder for all untrusted text
// ─────────────────────────────────────────────────────────────────────────────
// Decode one Unicode scalar from [p, end); advance p past what it consumed.
// Returns U+FFFD (REPLACEMENT CHARACTER) for every malformed, overlong,
// surrogate, or out-of-range sequence, consuming at least one byte on error so a
// hostile string always makes progress and can neither stall nor be read past
// `end`. This replaces the old ad-hoc decoder that understood only ₹ and fed
// every other multibyte byte through as a raw 0x80–0xFF "code point": that both
// garbled real Unicode names and was exactly the kind of unchecked byte-poking a
// crafted name could probe. The clamp to <= U+10FFFF keeps the value in range
// for stbtt, which returns an empty glyph for anything the font lacks.
static uint32_t next_utf8(const char *&p, const char *end)
{
    if (p >= end)
        return 0xFFFD;
    unsigned char b0 = (unsigned char)*p++;
    if (b0 < 0x80)
        return b0; // ASCII fast path

    uint32_t cp;
    int need;
    if ((b0 & 0xE0) == 0xC0) { cp = b0 & 0x1F; need = 1; }
    else if ((b0 & 0xF0) == 0xE0) { cp = b0 & 0x0F; need = 2; }
    else if ((b0 & 0xF8) == 0xF0) { cp = b0 & 0x07; need = 3; }
    else return 0xFFFD; // stray continuation byte or illegal 5/6-byte lead

    for (int i = 0; i < need; ++i)
    {
        if (p >= end)
            return 0xFFFD; // truncated at end of input
        unsigned char b = (unsigned char)*p;
        if ((b & 0xC0) != 0x80)
            return 0xFFFD; // not a continuation — resync WITHOUT consuming it
        cp = (cp << 6) | (uint32_t)(b & 0x3F);
        ++p;
    }

    static const uint32_t min_cp[4] = {0, 0x80, 0x800, 0x10000};
    if (cp < min_cp[need])       return 0xFFFD; // overlong encoding
    if (cp > 0x10FFFF)           return 0xFFFD; // outside Unicode
    if (cp >= 0xD800 && cp <= 0xDFFF) return 0xFFFD; // UTF-16 surrogate half
    return cp;
}

// ─────────────────────────────────────────────────────────────────────────────
// Font — thin wrapper around stbtt
// ─────────────────────────────────────────────────────────────────────────────
struct Font
{
    stbtt_fontinfo info;
    float scale = 0.f;
    int ascent = 0;
    int descent = 0;
    int line_gap = 0;

    bool load(const unsigned char *data)
    {
        if (!stbtt_InitFont(&info, data, 0))
            return false;
        return true;
    }

    void set_size(float px_height)
    {
        scale = stbtt_ScaleForPixelHeight(&info, px_height);
        stbtt_GetFontVMetrics(&info, &ascent, &descent, &line_gap);
    }

    // draw a UTF-8 string — returns x advance so caller knows where it ended
    // letter_spacing: extra pixels between glyphs (can be fractional via float)
    int draw(Canvas &canvas, const char *text, int x, int y,
             RGBA colour, float letter_spacing = 0.f) const
    {
        int baseline = y + (int)(ascent * scale);
        int cx = x;
        const char *p = text;
        const char *end = text + std::strlen(text);
        while (p < end)
        {
            uint32_t cp = next_utf8(p, end);
            const GlyphBitmap &g = glyph_get(&info, (int)cp, scale);
            if (!g.data.empty())
                canvas.blit_glyph(g.data.data(), g.w, g.h,
                                  cx + g.xoff, baseline + g.yoff, colour);
            cx += (int)(g.advance_f + letter_spacing);
        }
        return cx;
    }

    // measure string width without drawing
    int measure(const char *text, float letter_spacing = 0.f) const
    {
        int cx = 0;
        const char *p = text;
        const char *end = text + std::strlen(text);
        while (p < end)
        {
            uint32_t cp = next_utf8(p, end);
            const GlyphBitmap &g = glyph_get(&info, (int)cp, scale);
            cx += (int)(g.advance_f + letter_spacing);
        }
        return cx;
    }
};

// ─────────────────────────────────────────────────────────────────────────────
// Business-suffix helpers
// ─────────────────────────────────────────────────────────────────────────────

// Split a company name into {base, suffix}.  suffix is "" when not detected.
// Recognised suffixes (case-insensitive, must be preceded by space or comma):
//   Private Limited, Pvt. Ltd., Pvt Ltd, Limited, Ltd., Ltd
//   L.L.C., LLC,  L.L.P., LLP,  Inc., Inc,  Co., Co
static std::pair<std::string, std::string> split_business_suffix(const std::string &name)
{
    struct Entry
    {
        const char *lower;
        const char *display;
    };
    static const Entry table[] = {
        {"private limited", "Private Limited"},
        {"pvt. ltd.", "Pvt. Ltd."},
        {"pvt. ltd", "Pvt. Ltd"},
        {"pvt ltd.", "Pvt Ltd."},
        {"pvt ltd", "Pvt Ltd"},
        {"limited", "Limited"},
        {"ltd.", "Ltd."},
        {"ltd", "Ltd"},
        {"l.l.c.", "L.L.C."},
        {"llc", "LLC"},
        {"l.l.p.", "L.L.P."},
        {"llp", "LLP"},
        {"inc.", "Inc."},
        {"inc", "Inc"},
        {"co.", "Co."},
        {"co", "Co"},
        {nullptr, nullptr},
    };

    // lowercase copy for case-insensitive matching
    std::string low = name;
    for (auto &c : low)
        c = (char)std::tolower((unsigned char)c);

    for (int i = 0; table[i].lower; ++i)
    {
        const char *suf = table[i].lower;
        size_t suf_len = std::strlen(suf);
        if (low.size() <= suf_len)
            continue;

        // suffix must sit at the very end
        if (low.compare(low.size() - suf_len, suf_len, suf) != 0)
            continue;

        // the character immediately before the suffix must be a separator
        char sep = low[low.size() - suf_len - 1];
        if (sep != ' ' && sep != ',')
            continue;

        // base: everything before the separator, stripped
        std::string base = name.substr(0, low.size() - suf_len - 1);
        while (!base.empty() && (base.back() == ' ' || base.back() == ','))
            base.pop_back();

        return {base, table[i].display};
    }
    return {name, ""};
}

// Truncate text to fit max_w pixels, appending "…" if needed.
static std::string fit_or_truncate(Font &font, const std::string &text, int max_w)
{
    if (font.measure(text.c_str()) <= max_w)
        return text;
    std::string t = text;
    while (!t.empty() && font.measure((t + "\xe2\x80\xa6").c_str()) > max_w)
        t.pop_back();
    return t + "\xe2\x80\xa6"; // UTF-8 ellipsis U+2026
}

// Normalize/format incoming date strings into a human-friendly form:
// e.g. "2026-03-30" or "30 Mar 2026" -> "30 March 2026 Tuesday"
static std::string format_date_display(const std::string &in)
{
    auto trim = [](const std::string &s) -> std::string
    {
        size_t a = s.find_first_not_of(" \t\r\n");
        if (a == std::string::npos)
            return "";
        size_t b = s.find_last_not_of(" \t\r\n");
        return s.substr(a, b - a + 1);
    };

    std::string s = trim(in);
    if (s.empty())
        return s;

    // map month short -> number
    auto month_from_name = [](const std::string &mstr) -> int
    {
        if (mstr.empty())
            return -1;
        std::string low;
        for (char c : mstr)
            low.push_back((char)std::tolower((unsigned char)c));
        if (low.size() >= 3)
            low = low.substr(0, 3);
        static const char *tbl[] = {"jan", "feb", "mar", "apr", "may", "jun", "jul", "aug", "sep", "oct", "nov", "dec"};
        for (int i = 0; i < 12; ++i)
            if (low == tbl[i])
                return i + 1;
        return -1;
    };

    int y = 0, m = 0, d = 0;

    // Try ISO-like YYYY-MM-DD
    if (sscanf(s.c_str(), "%d-%d-%d", &y, &m, &d) == 3 && y > 0 && m >= 1 && m <= 12 && d >= 1 && d <= 31)
    {
        // parsed successfully
    }
    else
    {
        // try space-separated tokens: "30 Mar 2026" or "2026 Mar 30"
        std::istringstream iss(s);
        std::string a, b, c;
        if (!(iss >> a))
            return in;
        if (!(iss >> b))
            return in;
        if (!(iss >> c))
            return in;

        // case: "d mon yyyy"
        if (c.size() == 4 && std::isdigit((unsigned char)c[0]))
        {
            try
            {
                d = std::stoi(a);
                m = month_from_name(b);
                y = std::stoi(c);
            }
            catch (...)
            {
                return in;
            }
        }
        // case: "yyyy mon d"
        else if (a.size() == 4 && std::isdigit((unsigned char)a[0]))
        {
            try
            {
                y = std::stoi(a);
                m = month_from_name(b);
                d = std::stoi(c);
            }
            catch (...)
            {
                return in;
            }
        }
        else
        {
            return in;
        }
        if (m < 1 || m > 12 || d < 1 || d > 31)
            return in;
    }

    // compute weekday using Zeller's congruence (Gregorian)
    int Y = y;
    int M = m;
    int D = d;
    if (M <= 2)
    {
        M += 12;
        Y -= 1;
    }
    int K = Y % 100;
    int J = Y / 100;
    int h = (D + (13 * (M + 1)) / 5 + K + (K / 4) + (J / 4) + (5 * J)) % 7;
    // Zeller: 0=Saturday,1=Sunday,2=Monday,...
    static const char *wday[] = {"Saturday", "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday"};

    static const char *month_name[] = {"January", "February", "March", "April", "May", "June",
                                       "July", "August", "September", "October", "November", "December"};

    std::string out = std::to_string(d) + " " + month_name[m - 1] + " " + std::to_string(y) + " " + wday[h];
    return out;
}

// ─────────────────────────────────────────────────────────────────────────────
// Renderer
// ─────────────────────────────────────────────────────────────────────────────
struct Renderer
{
    Font fraunces; // name
    Font dmmono;   // labels, date, amount digits
    Font inter;    // rupee symbol (clean glyph)

    // The canvas is allocated ONCE and reused across every render. The daemon
    // is single-threaded (one render in flight), the size is fixed, and
    // `render()` clears it with `fill()` before drawing — so there is no reason
    // to malloc/free ~3 MB of RGBA per request. The PNG output buffer is the
    // only per-request allocation left, and it is reserved up front.
    Canvas canvas{IMG_W, IMG_H};

    bool init()
    {
        fpng::fpng_init();
        if (!fraunces.load(assets_Fraunces_Bold_ttf))
        {
            fprintf(stderr, "[err] failed to load Fraunces\n");
            return false;
        }
        if (!dmmono.load(assets_DMMono_Medium_ttf))
        {
            fprintf(stderr, "[err] failed to load DM Mono\n");
            return false;
        }
        if (!inter.load(assets_Inter_VariableFont_opsz_wght_ttf))
        {
            fprintf(stderr, "[err] failed to load Inter\n");
            return false;
        }
        printf("[ok] renderer ready\n");
        return true;
    }

    std::vector<uint8_t> render(const std::string &name,
                                const std::string &amount,
                                const std::string &date,
                                const Theme &theme)
    {
// #if PROFILE
// #define PROF_LAP(label)                                                             \
//     do                                                                              \
//     {                                                                               \
//         auto _now = std::chrono::steady_clock::now();                               \
//         fprintf(stderr, "  [prof] %-22s %6.0f µs\n", label,                         \
//                 std::chrono::duration<double, std::micro>(_now - _prof_t).count()); \
//         _prof_t = _now;                                                             \
//     } while (0)
//         auto _prof_start = std::chrono::steady_clock::now();
//         auto _prof_t = _prof_start;
// #else
#define PROF_LAP(label) (void)0
        // #endif

        // Reuse the member canvas (allocated once); `fill` clears last render.
        Canvas &canvas = this->canvas;

        // ── 1. background ─────────────────────────────────────────────────────
        canvas.fill(theme.bg);
        PROF_LAP("canvas.fill");

        // NOTE: top accent bar removed — embedding apps control their own chrome.

        // ── layout constants ──────────────────────────────────────────────────
        const int LEFT = SPX(80);
        const int RIGHT = IMG_W - SPX(80); // for right-aligned date
        int y = 0;

        // ── 3. split name into base + optional business suffix ────────────────
        auto [base_name, suffix] = split_business_suffix(name);

        // ── 4. sub-label: "BILLED TO" (larger for legibility)
        dmmono.set_size(SF(28.f));
        y = SPX(72);
        dmmono.draw(canvas, "BILLED TO", LEFT, y, theme.sub_label, SF(3.5f));
        PROF_LAP("BILLED TO");

        // ── 5. name (Fraunces Bold, auto-fitted) — allow larger max size
        const int NAME_MAX_W = RIGHT - LEFT;
        const float NAME_SZ_MAX = SF(110.f);
        const float NAME_SZ_MIN = SF(48.f);
        const float NAME_SZ_STEP = SF(4.f);

        float name_sz = NAME_SZ_MAX;
        fraunces.set_size(name_sz);
        while (name_sz > NAME_SZ_MIN && fraunces.measure(base_name.c_str()) > NAME_MAX_W)
        {
            name_sz -= NAME_SZ_STEP;
            fraunces.set_size(name_sz);
        }
        std::string display_name = fit_or_truncate(fraunces, base_name, NAME_MAX_W);

        y = SPX(120);
        fraunces.draw(canvas, display_name.c_str(), LEFT, y, theme.name);
        PROF_LAP("name draw");

        // compute bottom of name glyphs for next layout steps
        int name_baseline = y + (int)(fraunces.ascent * fraunces.scale);
        int name_bottom = name_baseline + (int)(std::abs(fraunces.descent) * fraunces.scale);

        // ── 6. business suffix label (if present)
        if (!suffix.empty())
        {
            dmmono.set_size(SF(26.f));
            int suf_y = name_bottom + SPX(8);
            dmmono.draw(canvas, suffix.c_str(), LEFT, suf_y, theme.sub_name, SF(1.5f));
            PROF_LAP("suffix draw");
            int suf_baseline = suf_y + (int)(dmmono.ascent * dmmono.scale);
            int suf_bottom = suf_baseline + (int)(std::abs(dmmono.descent) * dmmono.scale);
            if (suf_bottom > name_bottom)
                name_bottom = suf_bottom;
        }

        // ── 7. divider line (moved up to reduce empty space)
        int divider_y = name_bottom + SPX(36);
        canvas.rect(LEFT, divider_y, RIGHT - LEFT, std::max(1, SPX(1)), theme.divider);

        // ── 8. "TOTAL PAYABLE" label (larger)
        dmmono.set_size(SF(26.f));
        int total_label_y = divider_y + SPX(24);
        dmmono.draw(canvas, "TOTAL PAYABLE", LEFT, total_label_y, theme.amt_label, SF(3.5f));
        PROF_LAP("TOTAL PAYABLE");

        // ── 9. rupee symbol + amount — dynamic sizing (grow, then shrink to fit)
        const float AMOUNT_SZ_MAX = SF(160.f);
        const float AMOUNT_SZ_MIN = SF(36.f);
        const float AMOUNT_SZ_STEP = SF(4.f);
        const float RUPEE_RATIO = 0.7f; // rupee glyph ~70% of amount digit size — a ratio, unscaled
        const int AMOUNT_SPACING = SPX(8);

        float amt_sz = AMOUNT_SZ_MAX;
        int total_w = 0;
        while (true)
        {
            dmmono.set_size(amt_sz);
            inter.set_size(amt_sz * RUPEE_RATIO);
            int rupee_w = inter.measure("₹");
            int digits_w = dmmono.measure(amount.c_str());
            total_w = rupee_w + AMOUNT_SPACING + digits_w;
            if (total_w <= (RIGHT - LEFT) || amt_sz <= AMOUNT_SZ_MIN)
                break;
            amt_sz -= AMOUNT_SZ_STEP;
        }

        int amount_y = total_label_y + SPX(36);
        int amount_baseline = amount_y + (int)(dmmono.ascent * dmmono.scale);
        int rupee_top = amount_baseline - (int)(inter.ascent * inter.scale);
        int rupee_end = inter.draw(canvas, "₹", LEFT, rupee_top, theme.rupee);
        dmmono.draw(canvas, amount.c_str(), rupee_end + AMOUNT_SPACING, amount_y, theme.amount);
        PROF_LAP("rupee + amount");

        // ── 10. date — larger, bottom-right
        dmmono.set_size(SF(52.f));
        int date_y = IMG_H - SPX(64);
        int date_w = dmmono.measure(date.c_str());
        dmmono.draw(canvas, date.c_str(), RIGHT - date_w, date_y, theme.date);
        PROF_LAP("date");

        // ── 11. encode PNG ─────────────────────────────────────────────────────
        std::vector<uint8_t> out;
        // A flat-colour card of this size PNG-compresses to well under this;
        // reserving up front spares fpng its incremental regrowth.
        out.reserve(96 * 1024);
        fpng::fpng_encode_image_to_memory(canvas.px.data(), IMG_W, IMG_H, CH, out);
        PROF_LAP("png encode");

// #if PROFILE
//         double _total_us = std::chrono::duration<double, std::micro>(
//                                std::chrono::steady_clock::now() - _prof_start)
//                                .count();
//         fprintf(stderr, "  [prof] %-22s %6.0f µs\n", "--- TOTAL ---", _total_us);
// #endif
#undef PROF_LAP
        return out;
    }
};

// ─────────────────────────────────────────────────────────────────────────────
// UDS daemon
// protocol: client sends  "name\tamount\tdate\n"
//           server replies <4 bytes LE PNG size><4 bytes LE render_us><PNG bytes>
// Cap untrusted inputs before they reach the C++ font shaper — shared by every
// protocol backend, so it lives OUTSIDE their #if guards. A 64 KB company name
// is a slow-render DoS and needless exposure of stb_truetype to attacker length,
// and the card only shows what fits anyway. Truncation, not rejection — a long
// name still renders (fitted/ellipsised), just bounded.
// Cap the byte length (a DoS bound on glyph work per request) and drop C0 control
// bytes + DEL. Newlines, tabs and NULs have no place on a one-line card and only
// perturb layout; everything >= 0x20 is kept and the UTF-8 decoder validates the
// multibyte sequences at draw time. Truncation, not rejection — a long name still
// renders (fitted/ellipsised). A sequence cut mid-way by the byte cap is harmless:
// next_utf8 yields a single U+FFFD at the boundary and never over-reads.
static void sanitize_field(std::string &s, size_t max_bytes)
{
    if (s.size() > max_bytes)
        s.resize(max_bytes);
    std::string out;
    out.reserve(s.size());
    for (unsigned char c : s)
        if (c >= 0x20 && c != 0x7F)
            out.push_back((char)c);
    s.swap(out);
}

// Hard input-length caps, grounded in what the card can PHYSICALLY render rather
// than in some round number. The name area is NAME_MAX_W wide; the font auto-fits
// DOWN to NAME_SZ_MIN and is then ellipsised by fit_or_truncate, so it holds only
// ~40-45 glyphs at the smallest size. 128 bytes sits comfortably above that for
// any script — so the visible cut is always the ellipsis, never this hard cap —
// while still being a quarter of the old limit, which bounds the glyph
// measure/fit work a hostile 5000-char name would otherwise cost. The amount is a
// paise integer (20 digits is already 10^18 rupees); the date is an ISO-ish
// string that format_date_display expands. Anything longer we literally cannot
// show, so we refuse to spend a single raster cycle on it — truncation upstream,
// ellipsis at draw.
static void bound_inputs(std::string &name, std::string &amount, std::string &date)
{
    sanitize_field(name, 128);
    sanitize_field(amount, 20);
    sanitize_field(date, 24);
}

// ─────────────────────────────────────────────────────────────────────────────
// ── Protocol backends ─────────────────────────────────────────────────────────
// Build with:
//   make release          → legacy UDS (default, tab-delimited)
//   make release PROTO=HTTP  → bare HTTP/1.0 over UDS
//   make release PROTO=FCGI  → FastCGI over UDS (nginx fastcgi_pass)

#if defined(PROTO_FCGI)

#pragma pack(push, 1)
struct FcgiHeader
{
    uint8_t version;
    uint8_t type;
    uint16_t request_id;  // big-endian
    uint16_t content_len; // big-endian
    uint8_t padding_len;
    uint8_t reserved;
};
#pragma pack(pop)

enum FcgiType : uint8_t
{
    FCGI_BEGIN_REQUEST = 1,
    FCGI_END_REQUEST = 3,
    FCGI_PARAMS = 4,
    FCGI_STDIN = 5,
    FCGI_STDOUT = 6,
};

static uint16_t be16(const uint8_t *p) { return (uint16_t)((p[0] << 8) | p[1]); }
static uint16_t to_be16(uint16_t v) { return (uint16_t)((v >> 8) | (v << 8)); }

static bool read_exact(int fd, uint8_t *dst, int n)
{
    while (n > 0)
    {
        int r = read(fd, dst, n);
        if (r <= 0)
            return false;
        dst += r;
        n -= r;
    }
    return true;
}

static void fcgi_write_record(int fd, uint8_t type, uint16_t req_id,
                              const uint8_t *data, uint16_t len)
{
    FcgiHeader hdr{};
    hdr.version = 1;
    hdr.type = type;
    hdr.request_id = to_be16(req_id);
    hdr.content_len = to_be16(len);
    write(fd, &hdr, sizeof(hdr));
    if (len)
        write(fd, data, len);
}

static std::string url_decode(const std::string &s)
{
    std::string r;
    for (int i = 0; i < (int)s.size();)
    {
        if (s[i] == '+')
        {
            r += ' ';
            ++i;
        }
        else if (s[i] == '%' && i + 2 < (int)s.size())
        {
            char h[3] = {s[i + 1], s[i + 2], 0};
            r += (char)strtol(h, nullptr, 16);
            i += 3;
        }
        else
            r += s[i++];
    }
    return r;
}

static std::string fcgi_extract_qs(const uint8_t *p, int len)
{
    int i = 0;
    while (i < len)
    {
        auto read_len = [&]() -> int
        {
            if (i >= len)
                return 0;
            if ((p[i] & 0x80) == 0)
                return p[i++];
            if (i + 4 > len)
                return 0;
            int v = ((p[i] & 0x7f) << 24) | (p[i + 1] << 16) | (p[i + 2] << 8) | p[i + 3];
            i += 4;
            return v;
        };
        int nlen = read_len(), vlen = read_len();
        if (i + nlen + vlen > len)
            break;
        std::string key((char *)p + i, nlen);
        i += nlen;
        std::string val((char *)p + i, vlen);
        i += vlen;
        if (key == "QUERY_STRING")
            return val;
    }
    return {};
}

static void parse_qs(const std::string &qs,
                     std::string &name, std::string &amount,
                     std::string &date, std::string &theme_id)
{
    size_t pos = 0;
    while (pos < qs.size())
    {
        size_t amp = qs.find('&', pos);
        if (amp == std::string::npos)
            amp = qs.size();
        std::string pair = qs.substr(pos, amp - pos);
        size_t eq = pair.find('=');
        if (eq != std::string::npos)
        {
            std::string k = pair.substr(0, eq);
            std::string v = url_decode(pair.substr(eq + 1));
            if (k == "company")
                name = v;
            else if (k == "amount")
                amount = v;
            else if (k == "date")
                date = v;
            else if (k == "theme")
                theme_id = v;
        }
        pos = amp + 1;
    }
}

static void handle_client_fcgi(int cli, Renderer &renderer)
{
    std::string name, amount, date, theme_id;
    uint16_t req_id = 1;

    while (true)
    {
        FcgiHeader hdr;
        if (!read_exact(cli, (uint8_t *)&hdr, sizeof(hdr)))
            return;

        uint16_t clen = be16((uint8_t *)&hdr.content_len);
        req_id = be16((uint8_t *)&hdr.request_id);

        std::vector<uint8_t> body(clen + hdr.padding_len);
        if (!body.empty() && !read_exact(cli, body.data(), body.size()))
            return;

        if (hdr.type == FCGI_PARAMS && clen > 0)
        {
            std::string qs = fcgi_extract_qs(body.data(), clen);
            if (!qs.empty())
                parse_qs(qs, name, amount, date, theme_id);
        }
        else if (hdr.type == FCGI_STDIN && clen == 0)
            break; // end of request
    }

    if (name.empty())
        return;
    bound_inputs(name, amount, date);

    const Theme &theme = theme_id.empty()
                             ? theme_for_amount(parse_amount_to_paise(amount.c_str()))
                             : theme_by_id(theme_id.c_str());

    date = format_date_display(date);
    // No per-request logging: this is a hot path serving untrusted input, a log
    // line per card is wasted I/O (and, in a long-lived process, would sit in a
    // never-flushed stdout buffer). Only startup and errors are logged.
    auto png = renderer.render(name, amount, date, theme);

    // STDOUT: headers + body (chunk if > 65535)
    char hdrs[256];
    int hlen = snprintf(hdrs, sizeof(hdrs),
                        "Content-Type: image/png\r\nContent-Length: %zu\r\n\r\n", png.size());
    fcgi_write_record(cli, FCGI_STDOUT, req_id, (uint8_t *)hdrs, (uint16_t)hlen);

    // chunk PNG into 65535-byte records
    size_t sent = 0;
    while (sent < png.size())
    {
        uint16_t chunk = (uint16_t)std::min<size_t>(65535, png.size() - sent);
        fcgi_write_record(cli, FCGI_STDOUT, req_id, png.data() + sent, chunk);
        sent += chunk;
    }

    fcgi_write_record(cli, FCGI_STDOUT, req_id, nullptr, 0); // end stream
    uint8_t end[8] = {};
    fcgi_write_record(cli, FCGI_END_REQUEST, req_id, end, 8);
}

#elif defined(PROTO_HTTP)

static std::string url_decode(const std::string &s)
{
    std::string r;
    for (int i = 0; i < (int)s.size();)
    {
        if (s[i] == '+')
        {
            r += ' ';
            ++i;
        }
        else if (s[i] == '%' && i + 2 < (int)s.size())
        {
            char h[3] = {s[i + 1], s[i + 2], 0};
            r += (char)strtol(h, nullptr, 16);
            i += 3;
        }
        else
            r += s[i++];
    }
    return r;
}

static void handle_client_http(int cli, Renderer &renderer)
{
    // read only first line
    char buf[2048] = {};
    int i = 0;
    char c;
    while (i < (int)sizeof(buf) - 1)
    {
        if (read(cli, &c, 1) <= 0)
            break;
        buf[i++] = c;
        if (i >= 2 && buf[i - 2] == '\r' && buf[i - 1] == '\n')
            break;
    }

    char *q = strchr(buf, '?');
    char *sp = q ? strchr(q, ' ') : nullptr;
    if (!q || !sp)
    {
        close(cli);
        return;
    }

    std::string qs(q + 1, sp);
    std::string name, amount, date, theme_id;

    size_t pos = 0;
    while (pos < qs.size())
    {
        size_t amp = qs.find('&', pos);
        if (amp == std::string::npos)
            amp = qs.size();
        std::string pair = qs.substr(pos, amp - pos);
        size_t eq = pair.find('=');
        if (eq != std::string::npos)
        {
            std::string k = pair.substr(0, eq);
            std::string v = url_decode(pair.substr(eq + 1));
            if (k == "company")
                name = v;
            else if (k == "amount")
                amount = v;
            else if (k == "date")
                date = v;
            else if (k == "theme")
                theme_id = v;
        }
        pos = amp + 1;
    }

    if (name.empty())
    {
        const char *r400 = "HTTP/1.0 400 Bad Request\r\nContent-Length: 0\r\n\r\n";
        write(cli, r400, strlen(r400));
        return;
    }
    bound_inputs(name, amount, date);

    const Theme &theme = theme_id.empty()
                             ? theme_for_amount(parse_amount_to_paise(amount.c_str()))
                             : theme_by_id(theme_id.c_str());

    date = format_date_display(date);
    auto png = renderer.render(name, amount, date, theme);

    char hdr[256];
    int hl = snprintf(hdr, sizeof(hdr),
                      "HTTP/1.0 200 OK\r\nContent-Type: image/png\r\nContent-Length: %zu\r\n\r\n",
                      png.size());
    write(cli, hdr, hl);
    write(cli, png.data(), png.size());
}

#endif

#if !defined(PROTO_FCGI) && !defined(PROTO_HTTP)
// Legacy tab-delimited UDS protocol, extracted into a function so the fork loop
// wraps it like the others. Does NOT close cli — the caller does.
static void handle_client_tab(int cli, Renderer &renderer)
{
    char buf[512] = {};
    read(cli, buf, sizeof(buf) - 1);
    std::string req(buf);
    auto t1 = req.find('\t');
    auto t2 = req.find('\t', t1 + 1);
    if (t1 == std::string::npos || t2 == std::string::npos)
        return;

    std::string name = req.substr(0, t1);
    std::string amount = req.substr(t1 + 1, t2 - t1 - 1);
    std::string date, theme_id;
    auto t3 = req.find('\t', t2 + 1);
    if (t3 == std::string::npos)
    {
        date = req.substr(t2 + 1);
        if (!date.empty() && date.back() == '\n')
            date.pop_back();
    }
    else
    {
        date = req.substr(t2 + 1, t3 - t2 - 1);
        theme_id = req.substr(t3 + 1);
        if (!theme_id.empty() && theme_id.back() == '\n')
            theme_id.pop_back();
    }

    bound_inputs(name, amount, date);
    const Theme &theme = theme_id.empty()
                             ? theme_for_amount(parse_amount_to_paise(amount.c_str()))
                             : theme_by_id(theme_id.c_str());

    date = format_date_display(date);
    auto png = renderer.render(name, amount, date, theme);
    uint32_t sz = (uint32_t)png.size();
    uint32_t render_us = 0;
    write(cli, &sz, 4);
    write(cli, &render_us, 4);
    write(cli, png.data(), png.size());
}
#endif

// Protocol dispatch, selected at compile time.
static void handle_client(int cli, Renderer &renderer)
{
#if defined(PROTO_FCGI)
    handle_client_fcgi(cli, renderer);
#elif defined(PROTO_HTTP)
    handle_client_http(cli, renderer);
#else
    handle_client_tab(cli, renderer);
#endif
}

// ─────────────────────────────────────────────────────────────────────────────
// run_daemon — forks per connection so one bad input cannot crash the daemon
// ─────────────────────────────────────────────────────────────────────────────
void run_daemon(Renderer &renderer)
{
    // Socket path from the environment, so the hardened unit can place it under
    // a RuntimeDirectory (/run/billpreview/) instead of world-writable /tmp;
    // defaults to SOCKET_PATH for the dev harness and back-compat.
    const char *sock = getenv("BILLPREVIEW_SOCKET");
    if (!sock || !*sock)
        sock = SOCKET_PATH;

    unlink(sock);
    int srv = socket(AF_UNIX, SOCK_STREAM, 0);
    if (srv < 0)
    {
        perror("socket");
        return;
    }

    sockaddr_un addr{};
    addr.sun_family = AF_UNIX;
    strncpy(addr.sun_path, sock, sizeof(addr.sun_path) - 1);

    if (bind(srv, (sockaddr *)&addr, sizeof(addr)) < 0)
    {
        perror("bind");
        return;
    }
    // A generous backlog: this daemon serves connections sequentially in one
    // long-lived process (no fork, no threads), so a burst of link-unfurls queues
    // in the kernel while each ~15 ms render completes rather than being refused.
    listen(srv, 128);

#if defined(PROTO_FCGI)
    printf("[ok] listening on %s  [FCGI]\n", sock);
#elif defined(PROTO_HTTP)
    printf("[ok] listening on %s  [HTTP]\n", sock);
#else
    printf("[ok] listening on %s  [UDS]\n", sock);
#endif
    fflush(stdout);

    // ONE long-lived process, connections served sequentially. We deliberately do
    // NOT fork per connection: a fork-per-request model turns "send a malformed
    // name" into a fork + page-table setup + crash + stack-unwind + reap cycle we
    // pay for and the attacker does not — a cheap way to spin up a storm of
    // processes whose only job is to die. The defence here is PREVENTION, not
    // containment: the parse path is made total (validated UTF-8 in Font::draw,
    // every raster write clipped in Canvas, inputs bounded in bound_inputs) so no
    // input reaches undefined behaviour, and the catch below converts any C++
    // exception (bad_alloc, length_error, ...) into a dropped request instead of
    // a std::terminate. The process stays up; the glyph cache persists across
    // requests instead of being discarded with every child; the systemd sandbox
    // plus Restart=always remain the backstop for a genuine (non-input) fault.
    while (true)
    {
        int cli = accept(srv, nullptr, nullptr);
        if (cli < 0)
            continue;

        try
        {
            handle_client(cli, renderer);
        }
        catch (const std::exception &e)
        {
            // A malformed request must never take the daemon down. Log for the
            // operator, drop this one connection (nginx returns 502 for it), serve
            // the next. Anything reaching here is an allocation/size failure, not a
            // memory-safety bug — those are prevented upstream, not caught.
            fprintf(stderr, "[err] handler exception: %s\n", e.what());
        }
        catch (...)
        {
            fprintf(stderr, "[err] handler exception (non-std)\n");
        }
        close(cli);
    }
}

// Pre-warm the glyph cache with a few representative cards BEFORE the accept loop
// starts, so the first real request is not cold. The hot, fixed-scale glyphs —
// the "BILLED TO"/"TOTAL PAYABLE" labels, the date, common Latin/digits — are
// rasterised once here and, because this is now a single long-lived process,
// persist in the cache for the daemon's whole life (the bounded LRU-ish clear in
// glyph_get is the only thing that ever evicts them).
static void prewarm(Renderer &r)
{
    struct Sample
    {
        const char *name, *amount, *date;
    };
    static const Sample samples[] = {
        {"Acme Industries Private Limited", "1234567", "2026-09-01"},
        {"Zeta Traders LLP", "999", "2026-01-15"},
        {"A", "50000000", "2026-12-31"},
    };
    for (const auto &s : samples)
    {
        std::string nm = s.name, amt = s.amount;
        std::string dt = format_date_display(s.date);
        const Theme &t = theme_for_amount(parse_amount_to_paise(amt.c_str()));
        (void)r.render(nm, amt, dt, t);
    }
}

// ─────────────────────────────────────────────────────────────────────────────
int main()
{
    Renderer r;
    if (!r.init())
        return 1;
    prewarm(r);
    run_daemon(r);
    return 0;
}