#include <cstdint>
#include <cstring>
#include <cstdio>
#include <cmath>
#include <vector>
#include <algorithm>
#include <string>
#include <chrono>
#include <sys/socket.h>
#include <sys/un.h>
#include <unistd.h>

// ── Vendor ────────────────────────────────────────────────────────────────────
#include "vendor/stb_truetype.h"
#include "vendor/fpng.h"

// ── Embedded assets (generated by xxd) ───────────────────────────────────────
#include "gen/font_fraunces.h" // assets/Fraunces-Bold.ttf
#include "gen/font_dmmono.h"   // assets/DMMono-Medium.ttf
#include "gen/font_inter.h"    // assets/Inter-VariableFont_opsz,wght.ttf

// ── Theme system ─────────────────────────────────────────────────────────────
#include "themes.h"

// ── Glyph rasterization cache ─────────────────────────────────────────────────
#include "glyph_cache.h"

// ── Canvas size ───────────────────────────────────────────────────────────────
static constexpr int IMG_W = 1200;
static constexpr int IMG_H = 630;
static constexpr int CH = 4; // RGBA

// Palette is now fully driven by the Theme system (see src/themes.h / themes.cpp).
// Themes are selected per-request via the optional 4th tab field in the protocol
// or fall back to an amount-based ladder (dark-purple → dark-slate).

// ── UDS ───────────────────────────────────────────────────────────────────────
static constexpr const char *SOCKET_PATH = "/tmp/billpreview.sock";

// ─────────────────────────────────────────────────────────────────────────────
// Canvas
// ─────────────────────────────────────────────────────────────────────────────
struct Canvas
{
    std::vector<uint8_t> px;
    int w, h;

    Canvas(int w, int h) : px(w * h * CH), w(w), h(h) {}

    // fill entire canvas with one colour
    void fill(RGBA c)
    {
        for (int i = 0; i < w * h; ++i)
        {
            px[i * CH + 0] = c.r;
            px[i * CH + 1] = c.g;
            px[i * CH + 2] = c.b;
            px[i * CH + 3] = c.a;
        }
    }

    // filled rectangle — no blending, solid
    void rect(int x, int y, int rw, int rh, RGBA c)
    {
        for (int row = y; row < y + rh; ++row)
        {
            if (row < 0 || row >= h)
                continue;
            for (int col = x; col < x + rw; ++col)
            {
                if (col < 0 || col >= w)
                    continue;
                uint8_t *p = px.data() + (row * w + col) * CH;
                p[0] = c.r;
                p[1] = c.g;
                p[2] = c.b;
                p[3] = c.a;
            }
        }
    }

    // blit a greyscale glyph bitmap with alpha blend onto canvas
    void blit_glyph(const uint8_t *bmp, int bw, int bh,
                    int dx, int dy, RGBA c)
    {
        for (int row = 0; row < bh; ++row)
        {
            for (int col = 0; col < bw; ++col)
            {
                int cx = dx + col, cy = dy + row;
                if (cx < 0 || cy < 0 || cx >= w || cy >= h)
                    continue;
                uint8_t alpha = bmp[row * bw + col];
                if (alpha == 0)
                    continue;
                uint8_t *p = px.data() + (cy * w + cx) * CH;
                // simple over blend
                uint16_t ia = 255 - alpha;
                p[0] = (uint8_t)((c.r * alpha + p[0] * ia) >> 8);
                p[1] = (uint8_t)((c.g * alpha + p[1] * ia) >> 8);
                p[2] = (uint8_t)((c.b * alpha + p[2] * ia) >> 8);
                p[3] = 255;
            }
        }
    }
};

// ─────────────────────────────────────────────────────────────────────────────
// Font — thin wrapper around stbtt
// ─────────────────────────────────────────────────────────────────────────────
struct Font
{
    stbtt_fontinfo info;
    float scale = 0.f;
    int ascent = 0;
    int descent = 0;
    int line_gap = 0;

    bool load(const unsigned char *data)
    {
        if (!stbtt_InitFont(&info, data, 0))
            return false;
        return true;
    }

    void set_size(float px_height)
    {
        scale = stbtt_ScaleForPixelHeight(&info, px_height);
        stbtt_GetFontVMetrics(&info, &ascent, &descent, &line_gap);
    }

    // draw a UTF-8 string — returns x advance so caller knows where it ended
    // letter_spacing: extra pixels between glyphs (can be fractional via float)
    int draw(Canvas &canvas, const char *text, int x, int y,
             RGBA colour, float letter_spacing = 0.f) const
    {
        int baseline = y + (int)(ascent * scale);
        int cx = x;
        for (const char *p = text; *p; ++p)
        {
            unsigned cp = (unsigned char)*p;

            // basic UTF-8 decode for ₹ (U+20B9 = 0xE2 0x82 0xB9)
            if (cp == 0xE2 && (unsigned char)*(p + 1) == 0x82 && (unsigned char)*(p + 2) == 0xB9)
            {
                cp = 0x20B9;
                p += 2;
            }

            const GlyphBitmap &g = glyph_get(&info, (int)cp, scale);
            if (!g.data.empty())
                canvas.blit_glyph(g.data.data(), g.w, g.h,
                                  cx + g.xoff, baseline + g.yoff, colour);
            cx += (int)(g.advance_f + letter_spacing);
        }
        return cx;
    }

    // measure string width without drawing
    int measure(const char *text, float letter_spacing = 0.f) const
    {
        int cx = 0;
        for (const char *p = text; *p; ++p)
        {
            unsigned cp = (unsigned char)*p;
            if (cp == 0xE2 && (unsigned char)*(p + 1) == 0x82 && (unsigned char)*(p + 2) == 0xB9)
            {
                cp = 0x20B9;
                p += 2;
            }
            const GlyphBitmap &g = glyph_get(&info, (int)cp, scale);
            cx += (int)(g.advance_f + letter_spacing);
        }
        return cx;
    }
};

// ─────────────────────────────────────────────────────────────────────────────
// Business-suffix helpers
// ─────────────────────────────────────────────────────────────────────────────

// Split a company name into {base, suffix}.  suffix is "" when not detected.
// Recognised suffixes (case-insensitive, must be preceded by space or comma):
//   Private Limited, Pvt. Ltd., Pvt Ltd, Limited, Ltd., Ltd
//   L.L.C., LLC,  L.L.P., LLP,  Inc., Inc,  Co., Co
static std::pair<std::string, std::string> split_business_suffix(const std::string &name)
{
    struct Entry
    {
        const char *lower;
        const char *display;
    };
    static const Entry table[] = {
        {"private limited", "Private Limited"},
        {"pvt. ltd.", "Pvt. Ltd."},
        {"pvt. ltd", "Pvt. Ltd"},
        {"pvt ltd.", "Pvt Ltd."},
        {"pvt ltd", "Pvt Ltd"},
        {"limited", "Limited"},
        {"ltd.", "Ltd."},
        {"ltd", "Ltd"},
        {"l.l.c.", "L.L.C."},
        {"llc", "LLC"},
        {"l.l.p.", "L.L.P."},
        {"llp", "LLP"},
        {"inc.", "Inc."},
        {"inc", "Inc"},
        {"co.", "Co."},
        {"co", "Co"},
        {nullptr, nullptr},
    };

    // lowercase copy for case-insensitive matching
    std::string low = name;
    for (auto &c : low)
        c = (char)std::tolower((unsigned char)c);

    for (int i = 0; table[i].lower; ++i)
    {
        const char *suf = table[i].lower;
        size_t suf_len = std::strlen(suf);
        if (low.size() <= suf_len)
            continue;

        // suffix must sit at the very end
        if (low.compare(low.size() - suf_len, suf_len, suf) != 0)
            continue;

        // the character immediately before the suffix must be a separator
        char sep = low[low.size() - suf_len - 1];
        if (sep != ' ' && sep != ',')
            continue;

        // base: everything before the separator, stripped
        std::string base = name.substr(0, low.size() - suf_len - 1);
        while (!base.empty() && (base.back() == ' ' || base.back() == ','))
            base.pop_back();

        return {base, table[i].display};
    }
    return {name, ""};
}

// Truncate text to fit max_w pixels, appending "…" if needed.
static std::string fit_or_truncate(Font &font, const std::string &text, int max_w)
{
    if (font.measure(text.c_str()) <= max_w)
        return text;
    std::string t = text;
    while (!t.empty() && font.measure((t + "\xe2\x80\xa6").c_str()) > max_w)
        t.pop_back();
    return t + "\xe2\x80\xa6"; // UTF-8 ellipsis U+2026
}

// Normalize/format incoming date strings into a human-friendly form:
// e.g. "2026-03-30" or "30 Mar 2026" -> "30 March 2026 Tuesday"
static std::string format_date_display(const std::string &in)
{
    auto trim = [](const std::string &s) -> std::string
    {
        size_t a = s.find_first_not_of(" \t\r\n");
        if (a == std::string::npos)
            return "";
        size_t b = s.find_last_not_of(" \t\r\n");
        return s.substr(a, b - a + 1);
    };

    std::string s = trim(in);
    if (s.empty())
        return s;

    // map month short -> number
    auto month_from_name = [](const std::string &mstr) -> int
    {
        if (mstr.empty())
            return -1;
        std::string low;
        for (char c : mstr)
            low.push_back((char)std::tolower((unsigned char)c));
        if (low.size() >= 3)
            low = low.substr(0, 3);
        static const char *tbl[] = {"jan", "feb", "mar", "apr", "may", "jun", "jul", "aug", "sep", "oct", "nov", "dec"};
        for (int i = 0; i < 12; ++i)
            if (low == tbl[i])
                return i + 1;
        return -1;
    };

    int y = 0, m = 0, d = 0;

    // Try ISO-like YYYY-MM-DD
    if (sscanf(s.c_str(), "%d-%d-%d", &y, &m, &d) == 3 && y > 0 && m >= 1 && m <= 12 && d >= 1 && d <= 31)
    {
        // parsed successfully
    }
    else
    {
        // try space-separated tokens: "30 Mar 2026" or "2026 Mar 30"
        std::istringstream iss(s);
        std::string a, b, c;
        if (!(iss >> a))
            return in;
        if (!(iss >> b))
            return in;
        if (!(iss >> c))
            return in;

        // case: "d mon yyyy"
        if (c.size() == 4 && std::isdigit((unsigned char)c[0]))
        {
            try
            {
                d = std::stoi(a);
                m = month_from_name(b);
                y = std::stoi(c);
            }
            catch (...)
            {
                return in;
            }
        }
        // case: "yyyy mon d"
        else if (a.size() == 4 && std::isdigit((unsigned char)a[0]))
        {
            try
            {
                y = std::stoi(a);
                m = month_from_name(b);
                d = std::stoi(c);
            }
            catch (...)
            {
                return in;
            }
        }
        else
        {
            return in;
        }
        if (m < 1 || m > 12 || d < 1 || d > 31)
            return in;
    }

    // compute weekday using Zeller's congruence (Gregorian)
    int Y = y;
    int M = m;
    int D = d;
    if (M <= 2)
    {
        M += 12;
        Y -= 1;
    }
    int K = Y % 100;
    int J = Y / 100;
    int h = (D + (13 * (M + 1)) / 5 + K + (K / 4) + (J / 4) + (5 * J)) % 7;
    // Zeller: 0=Saturday,1=Sunday,2=Monday,...
    static const char *wday[] = {"Saturday", "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday"};

    static const char *month_name[] = {"January", "February", "March", "April", "May", "June",
                                       "July", "August", "September", "October", "November", "December"};

    std::string out = std::to_string(d) + " " + month_name[m - 1] + " " + std::to_string(y) + " " + wday[h];
    return out;
}

// ─────────────────────────────────────────────────────────────────────────────
// Renderer
// ─────────────────────────────────────────────────────────────────────────────
struct Renderer
{
    Font fraunces; // name
    Font dmmono;   // labels, date, amount digits
    Font inter;    // rupee symbol (clean glyph)

    bool init()
    {
        fpng::fpng_init();
        if (!fraunces.load(assets_Fraunces_Bold_ttf))
        {
            fprintf(stderr, "[err] failed to load Fraunces\n");
            return false;
        }
        if (!dmmono.load(assets_DMMono_Medium_ttf))
        {
            fprintf(stderr, "[err] failed to load DM Mono\n");
            return false;
        }
        if (!inter.load(assets_Inter_VariableFont_opsz_wght_ttf))
        {
            fprintf(stderr, "[err] failed to load Inter\n");
            return false;
        }
        printf("[ok] renderer ready\n");
        return true;
    }

    std::vector<uint8_t> render(const std::string &name,
                                const std::string &amount,
                                const std::string &date,
                                const Theme &theme)
    {
// #if PROFILE
// #define PROF_LAP(label)                                                             \
//     do                                                                              \
//     {                                                                               \
//         auto _now = std::chrono::steady_clock::now();                               \
//         fprintf(stderr, "  [prof] %-22s %6.0f µs\n", label,                         \
//                 std::chrono::duration<double, std::micro>(_now - _prof_t).count()); \
//         _prof_t = _now;                                                             \
//     } while (0)
//         auto _prof_start = std::chrono::steady_clock::now();
//         auto _prof_t = _prof_start;
// #else
#define PROF_LAP(label) (void)0
        // #endif

        Canvas canvas(IMG_W, IMG_H);

        // ── 1. background ─────────────────────────────────────────────────────
        canvas.fill(theme.bg);
        PROF_LAP("canvas.fill");

        // NOTE: top accent bar removed — embedding apps control their own chrome.

        // ── layout constants ──────────────────────────────────────────────────
        const int LEFT = 80;
        const int RIGHT = IMG_W - 80; // for right-aligned date
        int y = 0;

        // ── 3. split name into base + optional business suffix ────────────────
        auto [base_name, suffix] = split_business_suffix(name);

        // ── 4. sub-label: "BILLED TO" (larger for legibility)
        dmmono.set_size(28.f);
        y = 72;
        dmmono.draw(canvas, "BILLED TO", LEFT, y, theme.sub_label, 3.5f);
        PROF_LAP("BILLED TO");

        // ── 5. name (Fraunces Bold, auto-fitted) — allow larger max size
        const int NAME_MAX_W = RIGHT - LEFT;
        const float NAME_SZ_MAX = 110.f;
        const float NAME_SZ_MIN = 48.f;
        const float NAME_SZ_STEP = 4.f;

        float name_sz = NAME_SZ_MAX;
        fraunces.set_size(name_sz);
        while (name_sz > NAME_SZ_MIN && fraunces.measure(base_name.c_str()) > NAME_MAX_W)
        {
            name_sz -= NAME_SZ_STEP;
            fraunces.set_size(name_sz);
        }
        std::string display_name = fit_or_truncate(fraunces, base_name, NAME_MAX_W);

        y = 120;
        fraunces.draw(canvas, display_name.c_str(), LEFT, y, theme.name);
        PROF_LAP("name draw");

        // compute bottom of name glyphs for next layout steps
        int name_baseline = y + (int)(fraunces.ascent * fraunces.scale);
        int name_bottom = name_baseline + (int)(std::abs(fraunces.descent) * fraunces.scale);

        // ── 6. business suffix label (if present)
        if (!suffix.empty())
        {
            dmmono.set_size(26.f);
            int suf_y = name_bottom + 8;
            dmmono.draw(canvas, suffix.c_str(), LEFT, suf_y, theme.sub_name, 1.5f);
            PROF_LAP("suffix draw");
            int suf_baseline = suf_y + (int)(dmmono.ascent * dmmono.scale);
            int suf_bottom = suf_baseline + (int)(std::abs(dmmono.descent) * dmmono.scale);
            if (suf_bottom > name_bottom)
                name_bottom = suf_bottom;
        }

        // ── 7. divider line (moved up to reduce empty space)
        int divider_y = name_bottom + 36;
        canvas.rect(LEFT, divider_y, RIGHT - LEFT, 1, theme.divider);

        // ── 8. "TOTAL PAYABLE" label (larger)
        dmmono.set_size(26.f);
        int total_label_y = divider_y + 24;
        dmmono.draw(canvas, "TOTAL PAYABLE", LEFT, total_label_y, theme.amt_label, 3.5f);
        PROF_LAP("TOTAL PAYABLE");

        // ── 9. rupee symbol + amount — dynamic sizing (grow, then shrink to fit)
        const float AMOUNT_SZ_MAX = 160.f;
        const float AMOUNT_SZ_MIN = 36.f;
        const float AMOUNT_SZ_STEP = 4.f;
        const float RUPEE_RATIO = 0.7f; // rupee glyph ~70% of amount digit size
        const int AMOUNT_SPACING = 8;

        float amt_sz = AMOUNT_SZ_MAX;
        int total_w = 0;
        while (true)
        {
            dmmono.set_size(amt_sz);
            inter.set_size(amt_sz * RUPEE_RATIO);
            int rupee_w = inter.measure("₹");
            int digits_w = dmmono.measure(amount.c_str());
            total_w = rupee_w + AMOUNT_SPACING + digits_w;
            if (total_w <= (RIGHT - LEFT) || amt_sz <= AMOUNT_SZ_MIN)
                break;
            amt_sz -= AMOUNT_SZ_STEP;
        }

        int amount_y = total_label_y + 36;
        int amount_baseline = amount_y + (int)(dmmono.ascent * dmmono.scale);
        int rupee_top = amount_baseline - (int)(inter.ascent * inter.scale);
        int rupee_end = inter.draw(canvas, "₹", LEFT, rupee_top, theme.rupee);
        dmmono.draw(canvas, amount.c_str(), rupee_end + AMOUNT_SPACING, amount_y, theme.amount);
        PROF_LAP("rupee + amount");

        // ── 10. date — larger, bottom-right
        dmmono.set_size(52.f);
        int date_y = IMG_H - 64;
        int date_w = dmmono.measure(date.c_str());
        dmmono.draw(canvas, date.c_str(), RIGHT - date_w, date_y, theme.date);
        PROF_LAP("date");

        // ── 11. encode PNG ─────────────────────────────────────────────────────
        std::vector<uint8_t> out;
        fpng::fpng_encode_image_to_memory(canvas.px.data(), IMG_W, IMG_H, CH, out);
        PROF_LAP("png encode");

// #if PROFILE
//         double _total_us = std::chrono::duration<double, std::micro>(
//                                std::chrono::steady_clock::now() - _prof_start)
//                                .count();
//         fprintf(stderr, "  [prof] %-22s %6.0f µs\n", "--- TOTAL ---", _total_us);
// #endif
#undef PROF_LAP
        return out;
    }
};

// ─────────────────────────────────────────────────────────────────────────────
// UDS daemon
// protocol: client sends  "name\tamount\tdate\n"
//           server replies <4 bytes LE PNG size><4 bytes LE render_us><PNG bytes>
// ─────────────────────────────────────────────────────────────────────────────
// ── Protocol backends ─────────────────────────────────────────────────────────
// Build with:
//   make release          → legacy UDS (default, tab-delimited)
//   make release PROTO=HTTP  → bare HTTP/1.0 over UDS
//   make release PROTO=FCGI  → FastCGI over UDS (nginx fastcgi_pass)

#if defined(PROTO_FCGI)

#pragma pack(push, 1)
struct FcgiHeader
{
    uint8_t version;
    uint8_t type;
    uint16_t request_id;  // big-endian
    uint16_t content_len; // big-endian
    uint8_t padding_len;
    uint8_t reserved;
};
#pragma pack(pop)

enum FcgiType : uint8_t
{
    FCGI_BEGIN_REQUEST = 1,
    FCGI_END_REQUEST = 3,
    FCGI_PARAMS = 4,
    FCGI_STDIN = 5,
    FCGI_STDOUT = 6,
};

static uint16_t be16(const uint8_t *p) { return (uint16_t)((p[0] << 8) | p[1]); }
static uint16_t to_be16(uint16_t v) { return (uint16_t)((v >> 8) | (v << 8)); }

static bool read_exact(int fd, uint8_t *dst, int n)
{
    while (n > 0)
    {
        int r = read(fd, dst, n);
        if (r <= 0)
            return false;
        dst += r;
        n -= r;
    }
    return true;
}

static void fcgi_write_record(int fd, uint8_t type, uint16_t req_id,
                              const uint8_t *data, uint16_t len)
{
    FcgiHeader hdr{};
    hdr.version = 1;
    hdr.type = type;
    hdr.request_id = to_be16(req_id);
    hdr.content_len = to_be16(len);
    write(fd, &hdr, sizeof(hdr));
    if (len)
        write(fd, data, len);
}

static std::string url_decode(const std::string &s)
{
    std::string r;
    for (int i = 0; i < (int)s.size();)
    {
        if (s[i] == '+')
        {
            r += ' ';
            ++i;
        }
        else if (s[i] == '%' && i + 2 < (int)s.size())
        {
            char h[3] = {s[i + 1], s[i + 2], 0};
            r += (char)strtol(h, nullptr, 16);
            i += 3;
        }
        else
            r += s[i++];
    }
    return r;
}

static std::string fcgi_extract_qs(const uint8_t *p, int len)
{
    int i = 0;
    while (i < len)
    {
        auto read_len = [&]() -> int
        {
            if (i >= len)
                return 0;
            if ((p[i] & 0x80) == 0)
                return p[i++];
            if (i + 4 > len)
                return 0;
            int v = ((p[i] & 0x7f) << 24) | (p[i + 1] << 16) | (p[i + 2] << 8) | p[i + 3];
            i += 4;
            return v;
        };
        int nlen = read_len(), vlen = read_len();
        if (i + nlen + vlen > len)
            break;
        std::string key((char *)p + i, nlen);
        i += nlen;
        std::string val((char *)p + i, vlen);
        i += vlen;
        if (key == "QUERY_STRING")
            return val;
    }
    return {};
}

static void parse_qs(const std::string &qs,
                     std::string &name, std::string &amount,
                     std::string &date, std::string &theme_id)
{
    size_t pos = 0;
    while (pos < qs.size())
    {
        size_t amp = qs.find('&', pos);
        if (amp == std::string::npos)
            amp = qs.size();
        std::string pair = qs.substr(pos, amp - pos);
        size_t eq = pair.find('=');
        if (eq != std::string::npos)
        {
            std::string k = pair.substr(0, eq);
            std::string v = url_decode(pair.substr(eq + 1));
            if (k == "company")
                name = v;
            else if (k == "amount")
                amount = v;
            else if (k == "date")
                date = v;
            else if (k == "theme")
                theme_id = v;
        }
        pos = amp + 1;
    }
}

static void handle_client_fcgi(int cli, Renderer &renderer)
{
    std::string name, amount, date, theme_id;
    uint16_t req_id = 1;

    while (true)
    {
        FcgiHeader hdr;
        if (!read_exact(cli, (uint8_t *)&hdr, sizeof(hdr)))
            return;

        uint16_t clen = be16((uint8_t *)&hdr.content_len);
        req_id = be16((uint8_t *)&hdr.request_id);

        std::vector<uint8_t> body(clen + hdr.padding_len);
        if (!body.empty() && !read_exact(cli, body.data(), body.size()))
            return;

        if (hdr.type == FCGI_PARAMS && clen > 0)
        {
            std::string qs = fcgi_extract_qs(body.data(), clen);
            if (!qs.empty())
                parse_qs(qs, name, amount, date, theme_id);
        }
        else if (hdr.type == FCGI_STDIN && clen == 0)
            break; // end of request
    }

    if (name.empty())
        return;

    const Theme &theme = theme_id.empty()
                             ? theme_for_amount(parse_amount_to_paise(amount.c_str()))
                             : theme_by_id(theme_id.c_str());

    date = format_date_display(date);
    printf("[fcgi] name=%-30s  amount=%-12s  date=%-12s  theme=%s\n",
           name.c_str(), amount.c_str(), date.c_str(), theme.id);
    fflush(stdout);

    auto t_start = std::chrono::steady_clock::now();
    auto png = renderer.render(name, amount, date, theme);
    auto t_end = std::chrono::steady_clock::now();
    uint32_t render_us = (uint32_t)std::chrono::duration_cast<std::chrono::microseconds>(t_end - t_start).count();
    printf("[render] %u µs  (%.2f ms)\n", render_us, render_us / 1000.f);
    fflush(stdout);

    // STDOUT: headers + body (chunk if > 65535)
    char hdrs[256];
    int hlen = snprintf(hdrs, sizeof(hdrs),
                        "Content-Type: image/png\r\nContent-Length: %zu\r\n\r\n", png.size());
    fcgi_write_record(cli, FCGI_STDOUT, req_id, (uint8_t *)hdrs, (uint16_t)hlen);

    // chunk PNG into 65535-byte records
    size_t sent = 0;
    while (sent < png.size())
    {
        uint16_t chunk = (uint16_t)std::min<size_t>(65535, png.size() - sent);
        fcgi_write_record(cli, FCGI_STDOUT, req_id, png.data() + sent, chunk);
        sent += chunk;
    }

    fcgi_write_record(cli, FCGI_STDOUT, req_id, nullptr, 0); // end stream
    uint8_t end[8] = {};
    fcgi_write_record(cli, FCGI_END_REQUEST, req_id, end, 8);
}

#elif defined(PROTO_HTTP)

static std::string url_decode(const std::string &s)
{
    std::string r;
    for (int i = 0; i < (int)s.size();)
    {
        if (s[i] == '+')
        {
            r += ' ';
            ++i;
        }
        else if (s[i] == '%' && i + 2 < (int)s.size())
        {
            char h[3] = {s[i + 1], s[i + 2], 0};
            r += (char)strtol(h, nullptr, 16);
            i += 3;
        }
        else
            r += s[i++];
    }
    return r;
}

static void handle_client_http(int cli, Renderer &renderer)
{
    // read only first line
    char buf[2048] = {};
    int i = 0;
    char c;
    while (i < (int)sizeof(buf) - 1)
    {
        if (read(cli, &c, 1) <= 0)
            break;
        buf[i++] = c;
        if (i >= 2 && buf[i - 2] == '\r' && buf[i - 1] == '\n')
            break;
    }

    char *q = strchr(buf, '?');
    char *sp = q ? strchr(q, ' ') : nullptr;
    if (!q || !sp)
    {
        close(cli);
        return;
    }

    std::string qs(q + 1, sp);
    std::string name, amount, date, theme_id;

    size_t pos = 0;
    while (pos < qs.size())
    {
        size_t amp = qs.find('&', pos);
        if (amp == std::string::npos)
            amp = qs.size();
        std::string pair = qs.substr(pos, amp - pos);
        size_t eq = pair.find('=');
        if (eq != std::string::npos)
        {
            std::string k = pair.substr(0, eq);
            std::string v = url_decode(pair.substr(eq + 1));
            if (k == "company")
                name = v;
            else if (k == "amount")
                amount = v;
            else if (k == "date")
                date = v;
            else if (k == "theme")
                theme_id = v;
        }
        pos = amp + 1;
    }

    if (name.empty())
    {
        const char *r400 = "HTTP/1.0 400 Bad Request\r\nContent-Length: 0\r\n\r\n";
        write(cli, r400, strlen(r400));
        return;
    }

    const Theme &theme = theme_id.empty()
                             ? theme_for_amount(parse_amount_to_paise(amount.c_str()))
                             : theme_by_id(theme_id.c_str());

    date = format_date_display(date);
    printf("[http] name=%-30s  amount=%-12s  date=%-12s  theme=%s\n",
           name.c_str(), amount.c_str(), date.c_str(), theme.id);
    fflush(stdout);

    auto t_start = std::chrono::steady_clock::now();
    auto png = renderer.render(name, amount, date, theme);
    auto t_end = std::chrono::steady_clock::now();
    uint32_t render_us = (uint32_t)std::chrono::duration_cast<std::chrono::microseconds>(t_end - t_start).count();
    printf("[render] %u µs  (%.2f ms)\n", render_us, render_us / 1000.f);
    fflush(stdout);

    char hdr[256];
    int hl = snprintf(hdr, sizeof(hdr),
                      "HTTP/1.0 200 OK\r\nContent-Type: image/png\r\nContent-Length: %zu\r\n\r\n",
                      png.size());
    write(cli, hdr, hl);
    write(cli, png.data(), png.size());
}

#endif

// ─────────────────────────────────────────────────────────────────────────────
// run_daemon — unchanged signature, protocol selected at compile time
// ─────────────────────────────────────────────────────────────────────────────
void run_daemon(Renderer &renderer)
{
    unlink(SOCKET_PATH);
    int srv = socket(AF_UNIX, SOCK_STREAM, 0);
    if (srv < 0)
    {
        perror("socket");
        return;
    }

    sockaddr_un addr{};
    addr.sun_family = AF_UNIX;
    strncpy(addr.sun_path, SOCKET_PATH, sizeof(addr.sun_path) - 1);

    if (bind(srv, (sockaddr *)&addr, sizeof(addr)) < 0)
    {
        perror("bind");
        return;
    }
    listen(srv, 8);

#if defined(PROTO_FCGI)
    printf("[ok] listening on %s  [FCGI]\n", SOCKET_PATH);
#elif defined(PROTO_HTTP)
    printf("[ok] listening on %s  [HTTP]\n", SOCKET_PATH);
#else
    printf("[ok] listening on %s  [UDS]\n", SOCKET_PATH);
#endif
    fflush(stdout);

    while (true)
    {
        int cli = accept(srv, nullptr, nullptr);
        if (cli < 0)
            continue;

#if defined(PROTO_FCGI)
        handle_client_fcgi(cli, renderer);
        close(cli);

#elif defined(PROTO_HTTP)
        handle_client_http(cli, renderer);
        close(cli);

#else
        // ── legacy tab-delimited UDS (original) ──────────────────────────────
        char buf[512] = {};
        read(cli, buf, sizeof(buf) - 1);
        std::string req(buf);
        auto t1 = req.find('\t');
        auto t2 = req.find('\t', t1 + 1);
        if (t1 == std::string::npos || t2 == std::string::npos)
        {
            close(cli);
            continue;
        }

        std::string name = req.substr(0, t1);
        std::string amount = req.substr(t1 + 1, t2 - t1 - 1);
        std::string date, theme_id;
        auto t3 = req.find('\t', t2 + 1);
        if (t3 == std::string::npos)
        {
            date = req.substr(t2 + 1);
            if (!date.empty() && date.back() == '\n')
                date.pop_back();
        }
        else
        {
            date = req.substr(t2 + 1, t3 - t2 - 1);
            theme_id = req.substr(t3 + 1);
            if (!theme_id.empty() && theme_id.back() == '\n')
                theme_id.pop_back();
        }

        const Theme &theme = theme_id.empty()
                                 ? theme_for_amount(parse_amount_to_paise(amount.c_str()))
                                 : theme_by_id(theme_id.c_str());

        date = format_date_display(date);
        printf("[req] name=%-30s  amount=%-12s  date=%-12s  theme=%s\n",
               name.c_str(), amount.c_str(), date.c_str(), theme.id);
        fflush(stdout);

        auto t_start = std::chrono::steady_clock::now();
        auto png = renderer.render(name, amount, date, theme);
        auto t_end = std::chrono::steady_clock::now();
        uint32_t render_us = (uint32_t)std::chrono::duration_cast<std::chrono::microseconds>(t_end - t_start).count();
        printf("[render] %u µs  (%.2f ms)\n", render_us, render_us / 1000.f);
        fflush(stdout);

        uint32_t sz = (uint32_t)png.size();
        write(cli, &sz, 4);
        write(cli, &render_us, 4);
        write(cli, png.data(), png.size());
        close(cli);
#endif
    }
}

// ─────────────────────────────────────────────────────────────────────────────
int main()
{
    Renderer r;
    if (!r.init())
        return 1;
    run_daemon(r);
    return 0;
}