#include <cstdint>
#include <cstring>
#include <cstdio>
#include <cmath>
#include <vector>
#include <string>
#include <sys/socket.h>
#include <sys/un.h>
#include <unistd.h>

// ── Vendor ────────────────────────────────────────────────────────────────────
#include "vendor/stb_truetype.h"
#include "vendor/stb_image_write.h"

// ── Embedded assets (generated by xxd) ───────────────────────────────────────
#include "gen/font_fraunces.h" // assets/Fraunces-Bold.ttf
#include "gen/font_dmmono.h"   // assets/DMMono-Medium.ttf

// ── Canvas size ───────────────────────────────────────────────────────────────
static constexpr int IMG_W = 1200;
static constexpr int IMG_H = 630;
static constexpr int CH = 4; // RGBA

// ── Option A dark — palette ───────────────────────────────────────────────────
//
//   Background      #0F0F0F   15  15  15
//   Accent bar      #6C63FF   108  99 255   (purple, top 3px line)
//   Sub-label       #4A4040   74  64  64    (muted warm grey)
//   Name            #F0EBE3   240 235 227   (warm off-white)
//   Divider         #2A2520   42  37  32    (subtle warm dark)
//   Amt label       #4A4040   74  64  64
//   Rupee accent    #6C63FF   108  99 255
//   Amount          #F0EBE3   240 235 227
//   Date            #3A3530   58  53  48    (very muted)

struct RGBA
{
    uint8_t r, g, b, a;
};
static constexpr RGBA COL_BG = {15, 15, 15, 255};
static constexpr RGBA COL_ACCENT = {108, 99, 255, 255};
static constexpr RGBA COL_SUBLABEL = {74, 64, 64, 255};
static constexpr RGBA COL_NAME = {240, 235, 227, 255};
static constexpr RGBA COL_DIVIDER = {42, 37, 32, 255};
static constexpr RGBA COL_AMT_LABEL = {74, 64, 64, 255};
static constexpr RGBA COL_RUPEE = {108, 99, 255, 255};
static constexpr RGBA COL_AMOUNT = {240, 235, 227, 255};
static constexpr RGBA COL_DATE = {58, 53, 48, 255};

// ── UDS ───────────────────────────────────────────────────────────────────────
static constexpr const char *SOCKET_PATH = "/tmp/billpreview.sock";

// ─────────────────────────────────────────────────────────────────────────────
// Canvas
// ─────────────────────────────────────────────────────────────────────────────
struct Canvas
{
    std::vector<uint8_t> px;
    int w, h;

    Canvas(int w, int h) : px(w * h * CH), w(w), h(h) {}

    // fill entire canvas with one colour
    void fill(RGBA c)
    {
        for (int i = 0; i < w * h; ++i)
        {
            px[i * CH + 0] = c.r;
            px[i * CH + 1] = c.g;
            px[i * CH + 2] = c.b;
            px[i * CH + 3] = c.a;
        }
    }

    // filled rectangle — no blending, solid
    void rect(int x, int y, int rw, int rh, RGBA c)
    {
        for (int row = y; row < y + rh; ++row)
        {
            if (row < 0 || row >= h)
                continue;
            for (int col = x; col < x + rw; ++col)
            {
                if (col < 0 || col >= w)
                    continue;
                uint8_t *p = px.data() + (row * w + col) * CH;
                p[0] = c.r;
                p[1] = c.g;
                p[2] = c.b;
                p[3] = c.a;
            }
        }
    }

    // blit a greyscale glyph bitmap with alpha blend onto canvas
    void blit_glyph(const uint8_t *bmp, int bw, int bh,
                    int dx, int dy, RGBA c)
    {
        for (int row = 0; row < bh; ++row)
        {
            for (int col = 0; col < bw; ++col)
            {
                int cx = dx + col, cy = dy + row;
                if (cx < 0 || cy < 0 || cx >= w || cy >= h)
                    continue;
                uint8_t alpha = bmp[row * bw + col];
                if (alpha == 0)
                    continue;
                uint8_t *p = px.data() + (cy * w + cx) * CH;
                // simple over blend
                uint16_t ia = 255 - alpha;
                p[0] = (uint8_t)((c.r * alpha + p[0] * ia) >> 8);
                p[1] = (uint8_t)((c.g * alpha + p[1] * ia) >> 8);
                p[2] = (uint8_t)((c.b * alpha + p[2] * ia) >> 8);
                p[3] = 255;
            }
        }
    }
};

// ─────────────────────────────────────────────────────────────────────────────
// Font — thin wrapper around stbtt
// ─────────────────────────────────────────────────────────────────────────────
struct Font
{
    stbtt_fontinfo info;
    float scale = 0.f;
    int ascent = 0;
    int descent = 0;
    int line_gap = 0;

    bool load(const unsigned char *data)
    {
        if (!stbtt_InitFont(&info, data, 0))
            return false;
        return true;
    }

    void set_size(float px_height)
    {
        scale = stbtt_ScaleForPixelHeight(&info, px_height);
        stbtt_GetFontVMetrics(&info, &ascent, &descent, &line_gap);
    }

    // draw a UTF-8 string — returns x advance so caller knows where it ended
    // letter_spacing: extra pixels between glyphs (can be fractional via float)
    int draw(Canvas &canvas, const char *text, int x, int y,
             RGBA colour, float letter_spacing = 0.f) const
    {
        int baseline = y + (int)(ascent * scale);
        int cx = x;
        for (const char *p = text; *p; ++p)
        {
            unsigned cp = (unsigned char)*p;

            // basic UTF-8 decode for ₹ (U+20B9 = 0xE2 0x82 0xB9)
            if (cp == 0xE2 && (unsigned char)*(p + 1) == 0x82 && (unsigned char)*(p + 2) == 0xB9)
            {
                cp = 0x20B9;
                p += 2;
            }

            int bw, bh, xoff, yoff;
            uint8_t *bmp = stbtt_GetCodepointBitmap(
                &info, 0, scale, (int)cp, &bw, &bh, &xoff, &yoff);

            if (bmp)
            {
                canvas.blit_glyph(bmp, bw, bh,
                                  cx + xoff, baseline + yoff, colour);
                stbtt_FreeBitmap(bmp, nullptr);
            }

            int advance, lsb;
            stbtt_GetCodepointHMetrics(&info, (int)cp, &advance, &lsb);
            cx += (int)(advance * scale + letter_spacing);
        }
        return cx;
    }

    // measure string width without drawing
    int measure(const char *text, float letter_spacing = 0.f) const
    {
        int cx = 0;
        for (const char *p = text; *p; ++p)
        {
            unsigned cp = (unsigned char)*p;
            if (cp == 0xE2 && (unsigned char)*(p + 1) == 0x82 && (unsigned char)*(p + 2) == 0xB9)
            {
                cp = 0x20B9;
                p += 2;
            }
            int advance, lsb;
            stbtt_GetCodepointHMetrics(&info, (int)cp, &advance, &lsb);
            cx += (int)(advance * scale + letter_spacing);
        }
        return cx;
    }
};

// ─────────────────────────────────────────────────────────────────────────────
// Renderer
// ─────────────────────────────────────────────────────────────────────────────
struct Renderer
{
    Font fraunces; // name
    Font dmmono;   // everything else

    bool init()
    {
        if (!fraunces.load(assets_Fraunces_Bold_ttf))
        {
            fprintf(stderr, "[err] failed to load Fraunces\n");
            return false;
        }
        if (!dmmono.load(assets_DMMono_Medium_ttf))
        {
            fprintf(stderr, "[err] failed to load DM Mono\n");
            return false;
        }
        printf("[ok] renderer ready\n");
        return true;
    }

    std::vector<uint8_t> render(const std::string &name,
                                const std::string &amount,
                                const std::string &date)
    {
        Canvas canvas(IMG_W, IMG_H);

        // ── 1. background ─────────────────────────────────────────────────────
        canvas.fill(COL_BG);

        // ── 2. top accent bar (3px, full width) ───────────────────────────────
        canvas.rect(0, 0, IMG_W, 3, COL_ACCENT);

        // ── layout constants ──────────────────────────────────────────────────
        const int LEFT = 80;
        const int RIGHT = IMG_W - 80; // for right-aligned date
        int y = 0;

        // ── 3. sub-label: "PAYMENT TO" ────────────────────────────────────────
        //    DM Mono 22px, uppercase, letter-spaced
        dmmono.set_size(22.f);
        y = 100;
        dmmono.draw(canvas, "BILLED TO", LEFT, y, COL_SUBLABEL, 3.5f);

        // ── 4. name (Fraunces Bold) ───────────────────────────────────────────
        fraunces.set_size(82.f);
        y = 148;
        fraunces.draw(canvas, name.c_str(), LEFT, y, COL_NAME);

        // ── 5. divider line ───────────────────────────────────────────────────
        y = 310;
        canvas.rect(LEFT, y, RIGHT - LEFT, 1, COL_DIVIDER);

        // ── 6. "TOTAL PAYABLE" label ──────────────────────────────────────────
        dmmono.set_size(20.f);
        y = 340;
        dmmono.draw(canvas, "TOTAL PAYABLE", LEFT, y, COL_AMT_LABEL, 3.f);

        // ── 7. rupee symbol (accent colour) + amount (off-white) ──────────────
        //    draw ₹ in accent, then the rest of the amount in off-white
        //    amount arrives as e.g. "12,500.00" — we prepend ₹ ourselves
        fraunces.set_size(110.f);
        y = 380;

        // draw ₹ in accent colour, get x position after it
        int rupee_end = fraunces.draw(canvas, "₹", LEFT, y, COL_RUPEE);

        // draw amount digits in off-white, with a small gap after ₹
        fraunces.draw(canvas, amount.c_str(), rupee_end + 8, y, COL_AMOUNT);

        // ── 8. date — DM Mono, bottom right ───────────────────────────────────
        dmmono.set_size(26.f);
        y = 560;
        // right-align: measure first, then offset
        int date_w = dmmono.measure(date.c_str());
        dmmono.draw(canvas, date.c_str(), RIGHT - date_w, y, COL_DATE);

        // ── 9. encode PNG ──────────────────────────────────────────────────────
        std::vector<uint8_t> out;
        stbi_write_png_to_func(
            [](void *ctx, void *data, int size)
            {
                auto *buf = static_cast<std::vector<uint8_t> *>(ctx);
                auto *bytes = static_cast<uint8_t *>(data);
                buf->insert(buf->end(), bytes, bytes + size);
            },
            &out, IMG_W, IMG_H, CH,
            canvas.px.data(), IMG_W * CH);
        return out;
    }
};

// ─────────────────────────────────────────────────────────────────────────────
// UDS daemon
// protocol: client sends  "name\tamount\tdate\n"
//           server replies <4 bytes LE size><PNG bytes>
// ─────────────────────────────────────────────────────────────────────────────
void run_daemon(Renderer &renderer)
{
    unlink(SOCKET_PATH);

    int srv = socket(AF_UNIX, SOCK_STREAM, 0);
    if (srv < 0)
    {
        perror("socket");
        return;
    }

    sockaddr_un addr{};
    addr.sun_family = AF_UNIX;
    strncpy(addr.sun_path, SOCKET_PATH, sizeof(addr.sun_path) - 1);

    if (bind(srv, (sockaddr *)&addr, sizeof(addr)) < 0)
    {
        perror("bind");
        return;
    }
    listen(srv, 8);
    printf("[ok] listening on %s\n", SOCKET_PATH);

    while (true)
    {
        int cli = accept(srv, nullptr, nullptr);
        if (cli < 0)
            continue;

        char buf[512] = {};
        read(cli, buf, sizeof(buf) - 1);

        std::string req(buf);
        auto t1 = req.find('\t');
        auto t2 = req.find('\t', t1 + 1);
        if (t1 == std::string::npos || t2 == std::string::npos)
        {
            close(cli);
            continue;
        }

        std::string name = req.substr(0, t1);
        std::string amount = req.substr(t1 + 1, t2 - t1 - 1);
        std::string date = req.substr(t2 + 1);
        if (!date.empty() && date.back() == '\n')
            date.pop_back();

        printf("[req] name=%-20s  amount=%-12s  date=%s\n",
               name.c_str(), amount.c_str(), date.c_str());

        auto png = renderer.render(name, amount, date);

        uint32_t sz = (uint32_t)png.size();
        write(cli, &sz, 4);
        write(cli, png.data(), png.size());
        close(cli);
    }
}

// ─────────────────────────────────────────────────────────────────────────────
int main()
{
    Renderer r;
    if (!r.init())
        return 1;
    run_daemon(r);
    return 0;
}